import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';
import { AccountProvider } from '@/components/context/accountContext';
import { TransactionProvider } from '@/components/context/transactionContext';

export const metadata = {
  title: 'dump-fun',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
     
      <body>
        <div className='status-bar'></div>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <AccountProvider>
                <TransactionProvider>
              <UiLayout links={links}>{children}</UiLayout>
              </TransactionProvider>
              </AccountProvider>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
